
import javax.swing.JOptionPane;

public class jFrame extends javax.swing.JFrame {

    public jFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPapel = new javax.swing.JButton();
        btnPedra = new javax.swing.JButton();
        btnTesoura = new javax.swing.JButton();
        lblComputador = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnZerarContador = new javax.swing.JButton();
        lblDerrotas = new javax.swing.JLabel();
        lblVirorias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Mistral", 1, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Joquempô");

        btnPapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_sem_nome__5_-removebg-preview.png"))); // NOI18N
        btnPapel.setText("papel");
        btnPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPapelActionPerformed(evt);
            }
        });

        btnPedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_sem_nome__4_-removebg-preview.png"))); // NOI18N
        btnPedra.setText("pedra");
        btnPedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedraActionPerformed(evt);
            }
        });

        btnTesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design_sem_nome__7_-removebg-preview.png"))); // NOI18N
        btnTesoura.setText("tesoura");
        btnTesoura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTesouraActionPerformed(evt);
            }
        });

        lblComputador.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        lblComputador.setText("computador");

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ganhe da maquina!");

        btnZerarContador.setText("Zerar contador");
        btnZerarContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZerarContadorActionPerformed(evt);
            }
        });

        lblDerrotas.setFont(new java.awt.Font("Dubai Light", 1, 36)); // NOI18N
        lblDerrotas.setForeground(new java.awt.Color(255, 0, 0));
        lblDerrotas.setText("Derrotas: 0");

        lblVirorias.setFont(new java.awt.Font("Dubai Light", 1, 36)); // NOI18N
        lblVirorias.setForeground(new java.awt.Color(51, 204, 0));
        lblVirorias.setText("Vitórias: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(75, 75, 75)))
                .addGap(244, 244, 244)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDerrotas)
                    .addComponent(lblVirorias))
                .addGap(132, 132, 132))
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(btnPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnPedra, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnTesoura, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(380, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblComputador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnZerarContador)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTesoura, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPedra, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(lblComputador)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVirorias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDerrotas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnZerarContador)
                        .addGap(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   private int contadorVitoria = 0;
    private int contadorDerrota = 0;

    private void jogar(int escolhaJogador) {
        String[] opcoes = {"papel", "pedra", "tesoura"};
        int escolhaComputador = new java.util.Random().nextInt(3);
        lblComputador.setText("Computador: " + opcoes[escolhaComputador]);

        String resultado;
        if (escolhaComputador == escolhaJogador) {
            resultado = "empate";
        } else if ((escolhaJogador == 1 && escolhaComputador == 2)
                || // Pedra ganha da Tesoura
                (escolhaJogador == 0 && escolhaComputador == 1)
                || // Papel ganha da Pedra
                (escolhaJogador == 2 && escolhaComputador == 0) // Tesoura ganha do Papel
                ) {
            resultado = "Você venceu!";
            contadorVitoria++;

        } else {
            resultado = "Você perdeu!";
            contadorDerrota++;
        }
        JOptionPane.showMessageDialog(null, resultado);
        lblVirorias.setText("Vitórias: " + contadorVitoria);
        lblDerrotas.setText("Derrotas: " + contadorDerrota);
    }
    private void btnPedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedraActionPerformed
        jogar(1);
    }//GEN-LAST:event_btnPedraActionPerformed

    private void btnPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPapelActionPerformed
        jogar(0);
    }//GEN-LAST:event_btnPapelActionPerformed

    private void btnTesouraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTesouraActionPerformed
        jogar(2);
    }//GEN-LAST:event_btnTesouraActionPerformed

    private void btnZerarContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZerarContadorActionPerformed
        contadorVitoria = 0;
    contadorDerrota = 0;

    lblVirorias.setText("Vitórias: 0");
    lblDerrotas.setText("Derrotas: 0");
    }//GEN-LAST:event_btnZerarContadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPapel;
    private javax.swing.JButton btnPedra;
    private javax.swing.JButton btnTesoura;
    private javax.swing.JButton btnZerarContador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblComputador;
    private javax.swing.JLabel lblDerrotas;
    private javax.swing.JLabel lblVirorias;
    // End of variables declaration//GEN-END:variables
}
